### ISSUE TITLE
create an easyer way to change the banner

### ISSUE THREAD

**Issue by lostfile1** [fgahr/termchan#2]
I really want to change the banner but don't know much about golang I looked at the fmt folder but I'm afraid I may break it

**Comment by fgahr** [comment]
Thanks for your interest. I haven't looked at this project in a while and I don't currently have an instance up and running.

Anyway: this is a great suggestion! Configurability really isn't great yet but I have learned quite a bit about that since I last looked at termchan.
I now have something in mind to allow changing the banner without recompiling. I'll have to change the way output is handled but I'm now really looking forward to this.

**Comment by lostfile1** [comment]
i also made a video on it its not very good but I have about 122 subs so some one will see it 
https://youtu.be/-VbjexmiElc

**Comment by lostfile1** [comment]
i meant to say welcome message or motd

**Comment by fgahr** [comment]
[https://github.com/fgahr/termchan/blob/adjustable-banner/template/welcome.template](https://github.com/fgahr/termchan/blob/adjustable-banner/template/welcome.template)
This is what I'm currently considering. It's not yet wired up or anything, just a draft for now, board and thread views yet to come. Will use the [template language from the Go stdlib](https://golang.org/pkg/text/template/). 
That would allow reloading templates on startup or receiving SIGHUP.
Suggestions welcome but I have yet to figure out all the details. Supporting both terminal and html output makes it tricky but I want to keep that :)

**Comment by lostfile1** [comment]
Thanks man

**Comment by fgahr** [comment]
Created a pull request, feel free to have a look at the branch and comment on it. Documentation of the new features is very bare bones, see if it works for you.
Had a lot of fun doing it so thanks already.

**Comment by lostfile1** [comment]
no probelm

**Comment by lostfile1** [comment]
i already started working on my own welcome message already :]
![Untitled](https://user-images.githubusercontent.com/41842361/103252245-f5c99080-4949-11eb-88a0-71a17d08c2d1.png)

**Comment by lostfile1** [comment]
But don't worry that's not the final banner i just seeing what i could do with it im probably gonna run it through the yggdrasil network or lokinet

**Comment by fgahr** [comment]
If you plan on having a public instance running (that invites trolls, no less), you might run into trouble because requests aren't checked in any way and I'm sure there's a couple other security features that are missing. I could see a huge request blowing up the server's memory (should at least check the ContentLength field). For now, running it through a tightened reverse proxy is probably a good idea.

Anyway, gonna merge the branch now. Feel free to report whatever issues you're experiencing and request more features.
More styling options (date formats, bold text, etc.) are also possible.

**Comment by lostfile1** [comment]
i will keep you posted
