### ISSUE TITLE
 using socket files

### ISSUE THREAD

**Issue by lostfile1** [fgahr/termchan#4]
i think using a sock file would make it faster when using a reverse Nginx proxy maybe make it a little bit more secure

**Comment by fgahr** [comment]
Implementing this is rather easy. I'm just weighing different options for making this configurable.
I don't like having tons of command line switches for services (it wouldn't be just a port number anymore) so it should be a file-based configuration.
On one hand sqlite-based config for defining boards (and at some point possibly other settings such as user bans) seems appropriate. Sqlite3 is a tool a termchan admin will need anyway.
On the other hand, board configuration could work well with a JSON-based configuration file and that could also handle things such as transport types and whatever else may come up.
If I leave the boards inside the sqlite db, the rest could be handled with an INI file, although that is always a bit limited and may prove insufficient.
I'm currently leaning towards JSON (for the boards as well) and dropping the config.db for now. It can be re-introduced when there's a better use case for it. But I'll give it some more thought before acting on this.

**Comment by fgahr** [comment]
As mentioned in the pull-request, termchan-cli in its current form is unlikely to ever support domain socket connections as it complicates configuration considerably for what I consider to be an edge case.
I think the feature works as expected. Please verify that it works for you, too.

Overall I'm now quite happy with JSON-based configuration.

**Comment by lostfile1** [comment]
i will test it in a moment or to I wonder if I can also try to get https working with it all using nignx

**Comment by fgahr** [comment]
I just played around a bit with an nginx reverse proxy setup and found that the permissions on the unix socket were too strict at first.
That could probably be fixed with user/group settings of the two services but for now I pushed a change setting permissions on the socket to 666 and that fixed the problem for me.
The permissions can also be adjusted from the outside with a simple chmod. I might make it configurable at some point since 666 is usually not a good default. Of course, the containing directory also needs to be readable and listable.

Other than that, it works flawlessly. Note that some of the header fields need to be adjusted in the proxy settings to make it work as expected.
